Update test_Bash_Configuration.yml

diff --git a/.github/workflows/test_Bash_Configuration.yml b/.github/workflows/test_Bash_Configuration.yml
--- a/.github/workflows/test_Bash_Configuration.yml
+++ b/.github/workflows/test_Bash_Configuration.yml
@@ -39,7 +39,7 @@ jobs:
 
       - name: Source .bashrc and test commands
         run: |
-          # executer source ~/.bashrc si il y a un retour d'erreur alors afficher le message d'erreur et quitter
+          # Execute source ~/.bashrc if there is an error return then display the error message and exit
           if ! source ~/.bashrc
           then
               echo "Error: source ~/.bashrc"
@@ -80,6 +80,14 @@ jobs:
 
       - name: Test aliases dynamically
         run: |
+          # Execute source ~/.bashrc if there is an error return then display the error message and exit
+          if ! source ~/.bashrc
+          then
+              echo "Error: source ~/.bashrc"
+              exit 1
+          fi
+          source ~/.bashrc
+          
           # Get list of aliases from my_alias command
           IFS=$'\n' read -r -d '' -a alias_list <<< "$(my_alias | sed 's/Alias ://g' | sed 's/ --> /=/g')"
           for alias_entry in "${alias_list[@]}"; do
@@ -94,6 +102,14 @@ jobs:
 
       - name: Test functions dynamically
         run: |
+          # Execute source ~/.bashrc if there is an error return then display the error message and exit
+          if ! source ~/.bashrc
+          then
+              echo "Error: source ~/.bashrc"
+              exit 1
+          fi
+          source ~/.bashrc
+          
           # Get list of functions from my_function command
           IFS=$'\n' read -r -d '' -a function_list <<< "$(my_function | sed 's/Function ://g' | sed 's/ --> /=/g')"
           for function_entry in "${function_list[@]}"; do
@@ -108,6 +124,14 @@ jobs:
 
       - name: Test exported variables dynamically
         run: |
+          # Execute source ~/.bashrc if there is an error return then display the error message and exit
+          if ! source ~/.bashrc
+          then
+              echo "Error: source ~/.bashrc"
+              exit 1
+          fi
+          source ~/.bashrc
+          
           # Get list of exported variables from my_export command
           IFS=$'\n' read -r -d '' -a variable_list <<< "$(my_export | sed 's/Export ://g' | sed 's/ --> /=/g')"
           for variable_entry in "${variable_list[@]}"; do
